### ISSUE TITLE
Change License to LGPLv3

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/LightningSDK#10]
Many robotics teams are still choosing not to Open Source their code. Technically, under the GPLv3 license, this means that they can not use our SDK. LGPv3 is essentially the same thing, but allowing use of the code within proprietary software. I think we should change the license to this.

**Comment by PranavMathur** [comment]
Shouldn't we want to be able to see how they are using our code?

**Comment by danielgrimshaw** [comment]
This will still allow that, but include teams that like proprietary code. They will still have to state that they use our libraries.

**Comment by ZachOhara** [comment]
I stand by our descision to use the full GPL text. I strongly believe that
all teams *should* open-source their code, and I believe we should lead by
example in this respect. Letting teams freely download and use our code
without this restriction (and very likely without our knowledge), will
both discredit any metrics we may have on actual use of our software, and
let teams continue to think that open source is not an important step.

Making our code more readily available will do more to benefit individual
teams, but I believe that requiring derivative code to be open will do more
to benefit the FTC community as a whole.

**Comment by JakeOhara** [comment]
Wouldn't it encourage more teams to move to open source code?

**Comment by danielgrimshaw** [comment]
I think right now it would just discourage the use of our sdk

**Comment by JakeOhara** [comment]
Issue's closed, so are we staying with GPL?

**Comment by PranavMathur** [comment]
We discussed in the facebook chat, ask Zach to see the discussion.
