### ISSUE TITLE
Change all authors to Thunderbots for a release version

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots5604/LightningSDK#5]
@Thunderbots5604/owners 
As FTC has just released this year's game, we should have a release version of the SDK ready to go. However, since this will be the visible version to judges, we should change all mentions of author to "Thunderbots"

**Comment by ZachOhara** [comment]
The purpose of the @author javadoc tag (assuming that's what you're talking about) is not to identify the organization responsible for that code, but rather to identify the *individuals* within that organization which are responsible for that code. The copyright statement identifies the organization that owns the intellectual property of the code.

The author tag is essentially a design-oriented version of git blame.
